"""Add new fields to Movie Model

Revision ID: c11c5a3842e5
Revises: 1a7aab2fb6b6
Create Date: 2024-09-08 13:30:33.241794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11c5a3842e5'
down_revision = '1a7aab2fb6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('genres', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('want_to_watch', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('added_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('review')
        batch_op.drop_column('rating')
        batch_op.drop_column('added_date')
        batch_op.drop_column('want_to_watch')
        batch_op.drop_column('genres')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
